version: "3.9"
services:
  chrome-headless-service:
    image: haos616/chrome-headless-service:0.1.0
    init: true
  chrome-headless-client:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    depends_on:
      - chrome-headless-service
    volumes:
      - ./:/opt/chrome-headless-client
